// Auto-generated by tools/gen-buildinfo.sh — do not edit manually
enum BuildInfo {
    static let commitHash = "d2a9c57"
    static let buildDate  = "2026-04-07 11:48"
    static let label      = "d2a9c57 · 2026-04-07 11:48"
}
