// Auto-generated by tools/gen-buildinfo.sh — do not edit manually
enum BuildInfo {
    static let commitHash = "518c5cc"
    static let buildDate  = "2026-04-05 07:59"
    static let label      = "518c5cc · 2026-04-05 07:59"
}
