// Auto-generated by tools/gen-buildinfo.sh — do not edit manually
enum BuildInfo {
    static let commitHash = "020ba9a"
    static let buildDate  = "2026-04-05 00:08"
    static let label      = "020ba9a · 2026-04-05 00:08"
}
