#!/bin/bash
# Generates Sources/SKUMenuBar/BuildInfo.swift with current git commit + timestamp.
# Run before building: swift build calls this via Package.swift plugin or manually.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$REPO_ROOT/Sources/SKUMenuBar/BuildInfo.swift"

COMMIT=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date "+%Y-%m-%d %H:%M")

cat > "$OUT" <<EOF
// Auto-generated by tools/gen-buildinfo.sh — do not edit manually
enum BuildInfo {
    static let commitHash = "$COMMIT"
    static let buildDate  = "$BUILD_DATE"
    static let label      = "$COMMIT · $BUILD_DATE"
}
EOF

echo "✅ BuildInfo.swift updated: $COMMIT · $BUILD_DATE"

# Invalidate Swift build cache for BuildInfo so it is always recompiled.
# Without this, incremental builds may skip recompiling and embed a stale timestamp.
find "$REPO_ROOT/.build" -name "BuildInfo.swift.o" -delete 2>/dev/null || true
find "$REPO_ROOT/.build" -name "BuildInfo*.o" -delete 2>/dev/null || true
